### ISSUE TITLE
duvida

### ISSUE THREAD

**Issue by ting560** [Ramys/Iptv-Brasil-2024#109]
tenho uma duvida, quando coloco uma de sua lista m3u no vlc, os canais ficam pulando após um certo tempo, por que?

**Comment by Ramys** [comment]
Você tem que ativar a opção de repeat 1 no vlc.
Dessa forma vc mantém o canal fixo.

**Comment by ting560** [comment]
tem algum programa ou outra forma de rodar perfeitamente

**Comment by Ramys** [comment]
Tem dois aplicativos para download na página inicial.
Tanto para windows quanto para android.
Funcionando normalmente.
Teste as listas nos aplicativos informado.
