### ISSUE TITLE
Erro de login

### ISSUE THREAD

**Issue by GeniShimada** [Ramys/Iptv-Brasil-2024#111]
Sexta dia 8 o login: Reginaldooliver1 voltou a funcionar 

Já ontem dia 09 voltou a dar erro 

![image](https://github.com/user-attachments/assets/2145a669-d746-4b93-9fd5-274aca06c458)

**Comment by GeniShimada** [comment]
Abraços

**Comment by Ramys** [comment]
Tá faltando a porta no url.
http://acsa.ws:80

**Comment by Ramys** [comment]
![Screenshot_20241110-092735](https://github.com/user-attachments/assets/59b26283-205c-4a84-aabe-c2eed115f1ef)
![Screenshot_20241110-092731](https://github.com/user-attachments/assets/c31187bf-0428-4ecc-976d-d22d8019ba91)

**Comment by GeniShimada** [comment]
> Tá faltando a porta no url.
> 
> http://acsa.ws:80

Mesmo colocando não funciona

**Comment by GeniShimada** [comment]
Ontem voltou a funcionar 
Hoje saiu do ar

**Comment by GeniShimada** [comment]
Ontem voltou a funcionar 
Hoje saiu do ar

**Comment by Ramys** [comment]
> Ontem voltou a funcionar Hoje saiu do ar

O url mudou para https://vptdlxun.online

**Comment by GeniShimada** [comment]
Oi Ramys 
Aquela lista de canais e filmes 
No login reginaldooliver 
Tem como colocar disponível ?
Ela era perfeita
