### ISSUE TITLE
Freeze constante

### ISSUE THREAD

**Issue by pedrosimao** [Ramys/Iptv-Brasil-2024#112]
Olá,
Testei o servidor [http://acsa.ws:80](http://acsa.ws/) em diversas plataformas. Android, computador entre outras e todos os streaming tem um freeze constante.
Gostaria de saber se conhece algum player ou tecnologia que evite esse problema.
No mais como posso ajudar no projeto? Estou atualmente a procura de servidores Xtream com canais franceses, alem dos brasileiros.
E potencialmente filmes em versão original, ao invés de dublado.

**Comment by Ramys** [comment]
Bom dia.
Por ter bastante pessoas usando a mesma lista, realmente irá acontecer essas travas no andamento do stream.
O VLC tem a opção de repeat muito mais rápido que qualquer outra apk de stream algo em torno de 1 segundo.
Tenho algumas listas aqui que é privada e somente um Ip está sendo utilizada.
Conheço uma pessoa que trabalha com lista disponíveis aqui mesmo na Github de vários países. Na minha opinião ele no momento é o melhor que conheço.
Você pode me enviar via Pull o que você tem para que eu possa liberar em raw aqui no projeto.
Agradeço por entrar em contato comigo e tb em querer ajudar no projeto.

**Comment by eletroswing** [comment]
@Ramys Consegue me passar uma chave privada? Ou servidor privado? vou clonar ele em uma VPS e deixar o trafego mais "acessivel" pq vou ta clonando os segmentos e enviando via CDN

**Comment by Ramys** [comment]
> @Ramys Consegue me passar uma chave privada? Ou servidor privado? vou clonar ele em uma VPS e deixar o trafego mais "acessivel" pq vou ta clonando os segmentos e enviando via CDN

Se você for disponibilizar para os seguidores do projeto... eu libero uma lista privativa para você.

**Comment by eletroswing** [comment]
Vou fazer melhor, a um tempo e eu tinha uma api publica voltada pra isso mas nao tinha visibilidade.
Com uma lista privada eu clono as streams e forneço elas a partir de uma cdn pra aumentar a disponibilidade e tento reviver junto essa api antiga, mas mantendo tudo aberto como voce segue atualmente.

Se possível, me adiciona no discord para discutirmos mais sobre: fountaikkj

**Comment by Ramys** [comment]
> Vou fazer melhor, a um tempo e eu tinha uma api publica voltada pra isso mas nao tinha visibilidade. Com uma lista privada eu clono as streams e forneço elas a partir de uma cdn pra aumentar a disponibilidade e tento reviver junto essa api antiga, mas mantendo tudo aberto como voce segue atualmente.
> 
> Se possível, me adiciona no discord para discutirmos mais sobre: fountaikkj

Não uso Discord.
Me passe o seu e-mail para que eu possa lhe enviar a lista.

**Comment by eletroswing** [comment]
claro, segue: fountaiplayer@gmail.com

**Comment by Ramys** [comment]
@eletroswing
Foi encaminhada para vc a lista com o url e o a pasta com os canais.
Qualquer dúvida me chame por aqui, de preferência abra uma nova questão.
Obrigado!
