### ISSUE TITLE
Filmes e séries com 5 tentativas.

### ISSUE THREAD

**Issue by BRUCKAO** [Ramys/Iptv-Brasil-2024#80]
Caro @Ramys , tudo bem amigo ? Espero que sim. Desde já quero parabenizar pela disponibilidade do seu tempo em corrigir tal falhas.

Estou aqui realizando testes e sempre utilizo o login

378724
pcapQ5
http://bdtb.io:80

Constantemente tem ocorrido travas de tentativas ao tentar executar algum conteúdo.

Segue captura de tela:
![Screenshot_20230919_202049_IPTV Smarters Pro](https://github.com/Ramys/Iptv-Brasil-2023/assets/101984884/89bcbef2-8688-406c-9ae3-ecf4dc66a190)

**Smartphone Samsung A51:**
 - Android 13

Smart Tv LG

Ambos utilizando app recomendado IPTV SMARTERS PRO.

Grande abraço.

**Comment by Ramys** [comment]
Aopa..
Qual filme vc tentou acessar?
Fiz um teste aqui nesse login e rodou.

**Comment by BRUCKAO** [comment]
Filmes da Guia Lançamento 
![Screenshot_20230920_132050_IPTV Smarters Pro](https://github.com/Ramys/Iptv-Brasil-2023/assets/101984884/66daf939-cf9b-4a38-a1ea-1e9cc5fb0b67)


E algumas séries aleatórias e animes

Stranger Things, Rick e Morty, Yu Yu Hakusho, Cavaleiros dos Zodíacos Omega, Dragon Ball entre algumas outras.

**Comment by BRUCKAO** [comment]
> Aopa.. Qual filme vc tentou acessar? Fiz um teste aqui nesse login e rodou. ![Screenshot_20230920-125138.png](https://user-images.githubusercontent.com/5787076/269344794-22cdd0ce-a8b7-4401-9171-e6c9583ef113.png)

@Ramys Qual o aplicativo que está usando ?

**Comment by Ramys** [comment]
Iptv smarters

**Comment by BRUCKAO** [comment]
> Iptv smarters
> 
> Entra com o mesmo usuário e senha.. Modifique somente o url por esse http://acsc.cc:80

@Ramys no caso o seu IPTV Smarters é no celular ?
Estou fazendo teste no que você indicou, tanto no Cel como notebook.

Testei aqui e os filmes e séries funcionaram. Irei continuar lhe passando o feedback.

Porém...

A TV ao vivo fica reconectando.
![Screenshot_20230920_163225_IPTV Smarters Pro](https://github.com/Ramys/Iptv-Brasil-2023/assets/101984884/a2c549ee-3e3e-4603-a96a-3e42038cd9a9)

**Comment by Ramys** [comment]
![Enviando Screenshot_20230920-172241.png …]()
Aqui tá de boa.

**Comment by BRUCKAO** [comment]
Será que tem alguma configuração em roteador precisa ser feita ? DNS ou outros

**Comment by Ramys** [comment]
Segue o print.
![Screenshot_20230920-172241.png](https://github.com/Ramys/Iptv-Brasil-2023/assets/5787076/2cf31182-a0c2-4239-90b2-e01ac1f6d2e8)

**Comment by Ramys** [comment]
Vc testou os sds e hds?

**Comment by BRUCKAO** [comment]
> Iptv smarters
> 
> Entra com o mesmo usuário e senha.. Modifique somente o url por esse http://acsc.cc:80

@Ramys então, mais cedo estava funcionando filmes e séries, testei novamente agora e voltou a fazer o carregamento.

Segue print.
![Screenshot_20230920_215339_IPTV Smarters Pro](https://github.com/Ramys/Iptv-Brasil-2023/assets/101984884/146a12fc-f03a-41f9-899a-6a002cea08cc)

**Comment by BRUCKAO** [comment]
> Vc testou os sds e hds?

Sim. Achei que algo como DNS poderia estar atrapalhando, testei em outras redes de wi-fi e 4g e realmente apresentar erros de reprodução tanto no TV Ao Vivo, como também em filmes e séries.

**Comment by BRUCKAO** [comment]
> > Iptv smarters
> > Entra com o mesmo usuário e senha.. Modifique somente o url por esse http://acsc.cc:80
> 
> @Ramys então, mais cedo estava funcionando filmes e séries nesse link que me informou, testei novamente agora e voltou a fazer o carregamento.
> 
> Segue print. ![Screenshot_20230920_215339_IPTV Smarters Pro](https://user-images.githubusercontent.com/101984884/269452961-146a12fc-f03a-41f9-899a-6a002cea08cc.jpg)

Se tiver algum outro link e não se importar em me passar para ir testando, te agradeço.

**Comment by BRUCKAO** [comment]
![Screenshot_20230920_220148_IPTV Smarters Pro](https://github.com/Ramys/Iptv-Brasil-2023/assets/101984884/da4352b9-1822-49dd-8898-45afcd66c7f3)

**Comment by Ramys** [comment]
Enfim...
Aqui tá rodando normalmente..
Vc modificou o url que falei?

**Comment by BRUCKAO** [comment]
> Enfim... Aqui tá rodando normalmente.. Vc modificou o url que falei?

Sim, modifiquei. Testei nas duas. No momento que vocêe passou a outra URL eu testei e funcionou.

Achei que poderia ser algo relacionado a DNS, porém troquei e e continuou os erros. 

Não sei se tem algum limite de conexão simultânea que acaba impedindo o funcionamento.

Tanto que tem horas que fica direto dando os erros e do nada volta a funcionar.

**Comment by tiagovieira075** [comment]
Estou com o mesmo problema. As vezes o filme roda de boas, mas a grande maioria fica dando esse erro e não carrega.

**Comment by adrian-learning** [comment]
O erro descrito também acontece comigo, deva acontecer com todos usuários. Vou relatar meus testes.

- Filmes e séries carregam normalmente, porém em certo momentos, não abrem (Na TV - não testei no celular).

- Canais carregam porém em certos momentos (10 a 40 segundos após abertos) para de reproduzir. No celular o player volta automaticamente após 3-5 segundos. Na TV não volta, é preciso regredir e abrir novamente o canal. Mesmo no celular voltando a reproduzir, isso acontece constantemente.

TV e celular foi utilizado o app IPTV Smarters Pro, além de outros que persistem os mesmos problemas.

**Comment by AiltonG4** [comment]
Imagino que seja por conta da adição de conteúdo novo, pois para mim funciona uma hora e depois para de funcionar por um tempo e quando vejo, alguns conteúdos foram adicionados. Mas tá de parabéns pelo projeto.
