### ISSUE TITLE
Nao ta funcionando do EUA.

### ISSUE THREAD

**Issue by alportblu** [Ramys/Iptv-Brasil-2024#86]
Estava funcionando ateh ontem a noite e agora parou.

Sabe o que pode ser? Nao eh soh na minha casa, tentei com laptop em outro internet e tb nao funcionou. 

To achando que o servidor bloqueou por GeoIP. 

Consegue verificar? 

Ja mando o PIX! :D hahahaha

**Comment by alportblu** [comment]
Acabei de ver mais abaixo nos problemas e tem mais gente com o mesmo problema. Entao nao sei se eh problema aqui por conta de estar fora do Brasil. Tentei ateh com VPN e nao funcionou. Segue o teste pelo smarters pro web.

![image](https://github.com/Ramys/Iptv-Brasil-2023/assets/59105422/3d114902-d94e-42e3-b5bd-3e5a186d15c4)

**Comment by Ramys** [comment]
Aopa..
Qual lista?
