### ISSUE TITLE
Filmes e Series não funcionam | stream travando

### ISSUE THREAD

**Issue by iqsilva** [Ramys/Iptv-Brasil-2024#90]
Tentei executar filmes e series pelo iptv smarters pro, não está sendo possível exibir os conteudos.

Ao executar os canais de streaming, está travando bastante.

Tem alguma ideia do que pode ser Ramys?

**Comment by Ramys** [comment]
Cara, caiu uma url ontem e até agora nada..
Tô sem saber o que houve nesse url.
Espero que seja resolvido logo.

**Comment by iqsilva** [comment]
Fico no aguardo! Obrigado pela resposta rápida

**Comment by Ramys** [comment]
> Fico no aguardo! Obrigado pela resposta rápida

Atualizei duas listas..
Faça um teste.

**Comment by iqsilva** [comment]
Agora está funcionando ambas as features, porém ainda na questão da streaming acontece de travar, tem ideia do que pode ser?

**Comment by Ramys** [comment]
Tem outra lista ai que pode ajudar..
Quando tiver mais tempo libero outras listas com mais ips.

**Comment by iqsilva** [comment]
Beleza, mas no caso do iptv smarters pro, como eu faria pra trocar a lista? Ou você ja criaria outro user?

**Comment by Ramys** [comment]
No celular?
