### ISSUE TITLE
Read.me

### ISSUE THREAD

**Issue by MSaldanha15** [Ramys/Iptv-Brasil-2024#93]
Estou tendo dificuldades em utilizar a IPTV, realizei o download dos dois arquivos para windows e android e não consigo entender o que poderia estar errado. Selecionei o seu nome e senha como descrito nos passos anteriores mas o URL sempre aparece um erro quando tento inserir no programa.

**Comment by BRUCKAO** [comment]
Caro Ramys, primeiramente agradeço o retorno do projeto.

Para eu fazer o teste no iptv smarters qual seria a URL ?

Grande abraço.

**Comment by Ramys** [comment]
Qual aplicativo e qual login e senha vc está usando?
