### ISSUE TITLE
Site de canais

### ISSUE THREAD

**Issue by Flaviosmoke** [Ramys/Iptv-Brasil-2024#95]
Boa tarde, primeiramente muito obrigado por compartilhar essa lista conosco, tenho uma dúvida: onde você pega esses links de canais? Gostaria de assistir alguns canais específicos direto dessas fontes, que não acho em lugar nenhum. Desde já agradeço

**Comment by Ramys** [comment]
Boa noite..
Na verdade eu procuro aqui mesmo na Github alguns iptv links e etc.
Vc pode criar uma lista para vc através dessa que passei . Criar lista em .m3u8 com os canais que vc preferir, depois só reverter em .rar aqui mesmo na Github na sua pasta pessoal..
É simples e dependendo da quantidade de canais que vc preferir será rápido.
Outro ponto é que vc pode criar uma lista dessa mesmo em uma pasta privada.

**Comment by BRUCKAO** [comment]
Qual o app Android e PC você recomenda para ler essas listas .m3u e .m3u8 ?

**Comment by Ramys** [comment]
Tem o download no início do projeto..
Tanto para PC quanto para android.
