### ISSUE TITLE
Credenciais inválidas - FormigaTV

### ISSUE THREAD

**Issue by rperobs** [Ramys/Iptv-Brasil-2024#96]
Boa noite,

Não sei se é algum problema do servidor para autenticar, porém não consigo mais me logar com as credenciais disponibilizadas.
Até dia 17/04 estava ok.

**Comment by samuelvalvassori** [comment]
Quando vou conectar com os dados no IPTV SMARTES  ele da erro de: 
url do servidor inválido.
