### ISSUE TITLE
Assistir os canais de tv

### ISSUE THREAD

**Issue by lucasdzuc** [Ramys/Iptv-Brasil-2024#98]
**Descreva o bug**
Adicionei a lista no Web Video Caster para assistir os canais de tv na SmartTV, mas o player se fecha sozinho.

E obrigatório está autenticado em alguma plataforma para conseguir assistir os canais?

**Comment by Ramys** [comment]
Não conheço esse apk.
E se for via web precisa de um link q consiga fazer repeat 1.
