### ISSUE TITLE
nao consigo colocar no iptv smarters

### ISSUE THREAD

**Issue by Madara-SZ** [Ramys/Iptv-Brasil-2024#99]
nao sei qual url colocar e nem qual o nome de usario nem a senha

**Comment by Ramys** [comment]
É só usar a base da lista.
Login: pamelaflores
Senha: 92446060a
Url: https://5ce.co:80

**Comment by fernandesyuri16** [comment]
![Screenshot_20240515-121715_IPTV Smarters Pro.png](https://github.com/Ramys/Iptv-Brasil-2024/assets/89111833/dca21f31-cfa1-4c3f-a2ba-2e42daa8c23e)

está dando detalhes inválidos

**Comment by fernandesyuri16** [comment]
Não loga

**Comment by Madara-SZ** [comment]
> É só usar a base da lista. Login: pamelaflores Senha: 92446060a Url: https://5ce.co:80

muito obrigado consegui aqui
![image](https://github.com/Ramys/Iptv-Brasil-2024/assets/96931402/20697fa9-61dd-47b2-bbb9-f0e6870ea7ce)

**Comment by fernandesyuri16** [comment]
como fez?

coloquei as mesmas credenciais, a mesma url e não vai

**Comment by Ramys** [comment]
> ![Screenshot_20240515-121715_IPTV Smarters Pro.png](https://private-user-images.githubusercontent.com/89111833/330862541-dca21f31-cfa1-4c3f-a2ba-2e42daa8c23e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MDE2NzAsIm5iZiI6MTcxNTkwMTM3MCwicGF0aCI6Ii84OTExMTgzMy8zMzA4NjI1NDEtZGNhMjFmMzEtY2ZhMS00YzNmLWEyYmEtMmU0MmRhYThjMjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDIzMTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MzAwNDJlNWM2NWUzZGZkZjRmYTE4NjhiMDNmODZiMjA1ZDNhOWM3NjRjMzI5MzQ3MGFmMjM0NTg5MGY5NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sqQo0KNjiViMEbyRAi6BhYkm5lx6801w6HSULTCP-Qk)
> 
> está dando detalhes inválidos

Onde está instalado esse apk?
Tv , celular, android ou ios?

**Comment by lucasdzuc** [comment]
Tem que esta com algum VPN ativado?

**Comment by lucasdzuc** [comment]
Tentei logar pela tv, mas esta dando erro de autenticação com o host

**Comment by fernandesyuri16** [comment]
não usem "https" usem apenas "http"
